### PR TITLE
release: 0.8.3

### PR DESCRIPTION
**Pull request by universalmind303**

### CODE REVIEW

**Comment by universalmind303** [comment]
@Brooooooklyn were the napi images recently updated? I'm getting some unexpected failures

https://github.com/pola-rs/nodejs-polars/actions/runs/6631860470/job/18016302921?pr=137

**Comment by Bidek56** [comment]
The error says: `clang': No such file or directory` this looks like a CI issue. Are we using old `android/sdk`?

**Comment by universalmind303** [comment]
> The error says: `clang': No such file or directory` this looks like a CI issue. Are we using old `android/sdk`?

We just use what's available on the runners. 

https://github.com/actions/runner-images/blob/75c3a75a803901854368855f72f414ca11bce0db/images/linux/Ubuntu2204-Readme.md

Which there should be `ANDROID_NDK_LATEST_HOME` available. So i don't think it's an issue with the runners.

there haven't been any changes to anything android related since sept 6 (0.8.2 release). https://github.com/actions/runner-images/commits/75c3a75a803901854368855f72f414ca11bce0db/images

**Comment by universalmind303** [comment]
looks like it was actually bumped from 25 -> 26. 

https://github.com/actions/runner-images/commit/a4234d46c7b5db3e2187af0db44790e1a898c802

**Comment by Bidek56** [comment]
@universalmind303 Did you see my note concerning [npm/*/packages.json](https://github.com/pola-rs/nodejs-polars/blob/main/npm/android-arm64/package.json)? They all have 0.7.2 version. Do we care? Thx

**Comment by Bidek56** [comment]
It looks like we need to lock Bun to 1.0. GA installs Bun 1.0.7 which breaks `ts:lint`

**Comment by Brooooooklyn** [comment]
@universalmind303 you can fix android build like this: https://github.com/Brooooooklyn/canvas/commit/dcd776814db6f8ad08ba7ce5debebb8599c4f94e

**Comment by universalmind303** [comment]
going to go ahead & merge this in as is (since the release is [technically deployed](https://www.npmjs.com/package/nodejs-polars/v/0.8.3)

I will try to work on fixing bun ci. 

@Bidek56 WRT [npm/*/packages.json](https://github.com/pola-rs/nodejs-polars/blob/main/npm/android-arm64/package.json). Those are part of the deployment. No need to touch them as they auto update when running the release.

**Pull request merged**
