### PR TITLE
Adding Decimal type

### LINKED ISSUE #209: Add support for Decimal DataType
It would be useful to have support for the [Decimal DataType](https://docs.rs/polars/latest/polars/datatypes/enum.DataType.html#variant.Decimal).

It's possible to read and execute on e.g parquet dataframes containing Decimal as type but it doesn't seem to be possible to create or cast new columns with/to Decimal as type.

### PR DESCRIPTION
**Pull request by Bidek56**
Adding Polars Decimal type, although this functionality is considered unstable in Polars ATM. To close #209

### CODE REVIEW

**Comment by Bidek56** [comment]
@universalmind303 Would you know how to fix this method for Decimal type? Thx

```
impl FromNapiValue for Wrap<ChunkedArray<Int128Type>> {
    unsafe fn from_napi_value(env: sys::napi_env, napi_val: sys::napi_value) -> JsResult<Self> {
        let arr = Array::from_napi_value(env, napi_val)?;
        let len = arr.len() as usize;
        let mut builder = PrimitiveChunkedBuilder::<Int128Type>::new("", len);
        for i in 0..len {
            match arr.get::<BigInt>(i as u32) {
                Ok(val) => match val {
                    Some(v) => {
                        let (v, _b) = v.get_i128();
                        builder.append_value(v)
                    }
                    None => builder.append_null(),
                },
                Err(_) => {
                    builder.append_null()
                }
            }
        }
        Ok(Wrap(builder.finish()))
    }
}
```

**Comment by Bidek56** [comment]
@flisky Would you know how to fix this method for Decimal type? Thx

**Comment by flisky** [comment]
You have to keep `scale` **at least**, although the type declared as [`Option<usize>`](https://docs.rs/polars/latest/polars/datatypes/enum.DataType.html#variant.Decimal), it's [required](https://docs.rs/polars-core/0.40.0/src/polars_core/chunked_array/logical/decimal.rs.html#119) actually. The Option is just user faced, and it should be resolved as soon as possible.

**Comment by stinodego** [comment]
I don't know, but looks like you're not currently implementing it for Decimal. You're implementing on `Int128` when you should be implementing on `Logical<DecimalType, Int128Type>`.

**Pull request closed without merging**
